name: "Get & install cached dependencies"
description: Get and install cached npm dependencies
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      id: caching
      uses: actions/cache@v4
      with:
        path: node_modules
        key: npm-dependencies-${{hashFiles('**/package-lock.json')}}
    - name: Install dependencies
      if: steps.caching.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
